# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meu-qoelho-mq.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13meu-qoelho-mq.proto\"/\n\x05Queue\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.QueueType*%\n\tQueueType\x12\n\n\x06SIMPLE\x10\x00\x12\x0c\n\x08MULTIPLE\x10\x01\x32.\n\x0bMeuQoelhoMq\x12\x1f\n\x0b\x63reateQueue\x12\x06.Queue\x1a\x06.Queue\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meu_qoelho_mq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUEUETYPE']._serialized_start=72
  _globals['_QUEUETYPE']._serialized_end=109
  _globals['_QUEUE']._serialized_start=23
  _globals['_QUEUE']._serialized_end=70
  _globals['_MEUQOELHOMQ']._serialized_start=111
  _globals['_MEUQOELHOMQ']._serialized_end=157
# @@protoc_insertion_point(module_scope)
